apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.name}}
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      volumes:
      - name: {{.Values.name}}
        configMap:
          name: {{.Values.name}}
      containers:
      - name: {{.Values.name}}
        image: cnfldemos/alpine-curl:3.10.2_7.65.1
        args: [ 
          "-s",
          "-X", "POST",
          "-H", "Content-Type: application/json",
          "--data", "@/etc/config/connector/{{.Values.name}}-config.json",
          "http://connectors:8083/connectors"
        ]
        volumeMounts:
          - name: {{.Values.name}} 
            mountPath: /etc/config/connector
      restartPolicy: Never
  backoffLimit: 1
