apiVersion: v1
kind: Pod
metadata:
  namespace: operator
  name: jump-box
spec:
  containers:
  - name: jump-box
    image: docker.io/confluentinc/cp-server-operator:5.3.0.0
    command: [sleep, "86400"]
    volumeMounts:
    - name: kafka-client-properties
      mountPath: /etc/kafka-client-properties/
  volumes:
  - name: kafka-client-properties
    secret:
      secretName: kafka-client.properties
