DROP STREAM clickstream;
DROP TABLE events_per_min;
DROP TABLE events_per_min_max_avg;
DROP TABLE clickstream_codes;
DROP TABLE pages_per_min;
DROP TABLE ERRORS_PER_MIN_ALERT;
DROP TABLE ERRORS_PER_MIN;
DROP STREAM ENRICHED_ERROR_CODES;
DROP TABLE ENRICHED_ERROR_CODES_COUNT;
DROP TABLE WEB_USERS;
DROP STREAM customer_clickstream;
DROP STREAM platinum_customers_with_errors;
DROP STREAM platinum_errors;
DROP TABLE PLATINUM_ERRORS_PER_5_MIN;
DROP TABLE platinum_page_errors_per_5_min;
DROP STREAM USER_CLICKSTREAM;
DROP TABLE USER_IP_ACTIVITY;
DROP TABLE CLICK_USER_SESSIONS;
DROP TABLE PER_USER_KBYTES;
DROP TABLE MALICIOUS_USER_SESSIONS;




