= Tutorial: Password Protection

== Introduction

Enterprises have compliance requirements to not store sensitive data as clear text in files.
For Apache Kafka in which services read configuration files on start-up, the question arises how should you protect passwords or other sensitive data in those configuration files?
Before Confluent Platform 5.3, you would have considered:

* restricting network access to the hosts running the services
* setting permissions on the configuration files using standard linux `ugo/rwx` settings
* adding OS-level ACLs for more user granularity

There was still a risk that a bad actor—a rogue employee or shoulder-surfer or hacker—could gain access to those files that contain passwords.
If you could tolerate a bit more complexity, you could also have encrypted volumes with specialized kernel modules that supported process-based ACLs or used the capabilities in link:https://cwiki.apache.org/confluence/display/KAFKA/KIP-226+-+Dynamic+Broker+Configuration#KIP-226-DynamicBrokerConfiguration-SecuringpasswordsinZooKeeper[KIP-226] to store encrypted passwords in ZooKeeper.

Even more useful and simpler is a solution that you let you encrypt the data that you wanted within the configuration file itself, so that even if someone gained access to those files, they couldn't read the sensitive data.
Introduced in Confluent Platform 5.3, there is a new security feature called Password Protection.
Instead of storing passwords or other sensitive data as clear text, password protection encrypts it within the configuration file itself.
Using this feature is the easiest way to manage sensitive data that needs to be written in Confluent Platform configuration files.
Even if someone gains access to and can read the configuration file, all they can see are encrypted values and they have no way to decrypt them.

We will step through a tutorial to get you started with this feature.
For a list of all relevant commands, please review link:https://docs.confluent.io/current/security/secrets.html[CLI reference].

== Setup

Before you start:

. Download link:https://www.confluent.io/download/[Confluent Platform 5.3] or higher
. Get the new link:https://docs.confluent.io/current/cli/installing.html[Confluent CLI] (v0.103.0 or above)

== Workflow

In the most common use case, you would want to encrypt passwords.
We have a link:https://docs.confluent.io/current/tutorials/security_tutorial.html[Security tutorial] that provides an example of how to enable security features on Confluent Platform, but that takes extra steps to generate the keys and certificates and add the TLS configurations.
Therefore, instead of encrypting a password, we will encrypt another configuration parameter, but the steps are exactly the same.

=== Generate the master key based on a passphrase

First choose your master key passphrase, a phrase that is much longer than a typical password and is easily remembered as a string of words.
Then choose the location of where the secrets file will reside on your local host (not where the Confluent Platform services run).
The secrets file will contain encrypted secrets for the master key, data key, and configuration parameters, along with their metadata such as which cipher was used for encryption.
Now you are ready to generate the master key:

[source,bash]
----
# passphrase: secure_your_data_with_Confluent_Platform_security
# local-secrets-file: /tmp/secrets.txt
$ confluent secret master-key generate --passphrase secure_your_data_with_Confluent_Platform_security --local-secrets-file /tmp/secrets.txt

Save the master key. It cannot be retrieved later.
+------------+----------------------------------------------+
| Master Key | Nf1IL2bmqRdEz2DO//gX2C+4PjF5j8hGXYSu9Na9bao= |
+------------+----------------------------------------------+
----

Export this key into the environment on the local host, as well as every host that will have a configuration file with password protection:

[source,bash]
----
$ export CONFLUENT_SECURITY_MASTER_KEY=Nf1IL2bmqRdEz2DO//gX2C+4PjF5j8hGXYSu9Na9bao=
----

View the contents of the local secrets file `/tmp/secrets.txt`:

[source,bash]
----
$ cat /tmp/secrets.txt
_metadata.master_key.0.salt = Hu+yLt10BNLLwwesoqthY5i1MgnejDhKrGSybeUEzbE=
_metadata.symmetric_key.0.created_at = 2019-06-26 14:05:34.469935 -0400 EDT m=+0.041116529
----

=== Encrypt the value of a configuration parameter

Let's use a configuration parameter available in a configuration file that ships with Confluent Platform.
We will encrypt the parameter `config.storage.topic` in `$CONFLUENT_HOME/etc/schema-registry/connect-avro-distributed.properties`.

First make a backup of this file, because the CLI currently does in-place modification on the original file.
Then choose the location of where the secrets file will reside on the remote hosts where the Confluent Platform services run.
Now you are ready to encrypt this field:

[source,bash]
----
# Value before encryption
$ grep "config\.storage\.topic" connect-avro-distributed.properties
config.storage.topic=connect-configs

# Encrypt it
# remote-secrets-file: /tmp/secrets-remote.txt
confluent secret file encrypt --local-secrets-file /tmp/secrets.txt --remote-secrets-file /tmp/secrets-remote.txt --config-file connect-avro-distributed.properties --config config.storage.topic

# Value after encryption
$ grep "config\.storage\.topic" connect-avro-distributed.properties
config.storage.topic = ${securepass:/tmp/secrets-remote.txt:connect-avro-distributed.properties/config.storage.topic}
----

As you can see, the configuration parameter `config.storage.topic` setting was changed from `connect-configs` to `${securepass:/tmp/secrets-remote.txt:connect-avro-distributed.properties/config.storage.topic}`.
This is a tuple that directs the service to use to look up the encrypted value of the file/parameter pair `connect-avro-distributed.properties/config.storage.topic` from the secrets file `/tmp/secrets-remote.txt`.

View the contents of the local secrets file `/tmp/secrets.txt`, which now contains the encrypted secret for this file/parameter pair along with the metadata, e.g. which cipher was used for encryption:

[source,bash]
----
$ cat /tmp/secrets.txt
...
connect-avro-distributed.properties/config.storage.topic = ENC[AES/CBC/PKCS5Padding,data:CUpHh5lRDfIfqaL49V3iGw==,iv:vPBmPkctA+yYGVQuOFmQJw==,type:str]
----

You can also decrypt the value into a file:

[source,bash]
----
$ confluent secret file decrypt --local-secrets-file /tmp/secrets.txt --config-file connect-avro-distributed.properties --output-file /tmp/decrypted.txt
$ cat /tmp/decrypted.txt
config.storage.topic = connect-configs
----

=== Distribute the secrets

There are two tasks to distribute the secrets:

. Distribute the secrets file: copy the secrets file `/tmp/secrets.txt` from the local host on which you have been working to `/tmp/secrets-remote.txt` on the destination hosts.
. Propagate the necessary configuration file changes: update the configuration file on all hosts so that the configuration parameter now has the tuple for secrets.

We recommend that you operationalize the workflow by augmenting your orchestration tooling (e.g. Confluent Ansible) to distribute this to the destination hosts.
These hosts may include Kafka brokers, Connect workers, Schema Registry instances, etc., any service using password encryption.

=== Update the value of the configuration parameter

You may have a requirement to update sensitive data on a regular basis, to help them from getting stale.
The configuration parameter `config.storage.topic` was originally set to `connect-configs`.
If you need to change the value in the future, you can update it directly using the CLI.
Let's say the new value is `newTopicName`.

[source,bash]
----
$ confluent secret file update --local-secrets-file /tmp/secrets.txt --remote-secrets-file /tmp/secrets-remote.txt --config-file connect-avro-distributed.properties --config config.storage.topic=newTopicName
----

The configuration file `connect-avro-distributed.properties` does not change because it's just a pointer to the secrets file.
However the secrets file has a new value for the encrypted value for this file/parameter pair:

[source,bash]
----
$ cat /tmp/secrets.txt
...
connect-avro-distributed.properties/config.storage.topic = ENC[AES/CBC/PKCS5Padding,data:CblF3k1ieNkFJzlJ51qAAA==,iv:dnZwEAm1rpLyf48pvy/T6w==,type:str]
----

=== Rotate the keys

You may also have a requirement to rotate the master key or data key on a regular basis.
You can do either of these with the CLI, and we will show you how to rotate the data key below.

[source,bash]
----
$ confluent secret file rotate --data-key --local-secrets-file /tmp/secrets.txt --passphrase secure_your_data_with_Confluent_Platform_security
----

