= Tutorial: Password Protection

== Introduction

Enterprises have compliance requirements to not store sensitive information as clear text in files.
For Apache Kafka in which services read configuration files on start-up, the question often arises how should you protect the passwords or other sensitive information that need to be specified in those configuration files?
Up to now, we have recommended locking down permissions on those configuration files so that only administrators can read those files.
But this still has a risk exposure that a bad actor, like a rogue employee or shoulder-surfer or hacker, can gain access to those files that contain passwords.
So what if we could address this such that even if bad actors gained access and could read those files, they still couldn't read the sensitive information?

Confluent Platform 5.3 introduces a new feature password protection to address this use case.
Password protection manages sensitive information that needs to be specified in Confluent Platform configuration files.
Instead of storing sensitive information as clear text, password protection encrypts the information so the configuration file stores the encrypted values.
It can apply to passwords or any other field in the configuration file.
Even if someone can read the configuration file, all they see are encrypted values and they have no way to decrypt them.

We will step through a tutorial to get you started with this feature.
For a list of all relevant commands, please review link:https://docs.confluent.io/current/security/secrets.html[CLI reference].

== Setup

Before you start:

* Download link:https://www.confluent.io/download/[Confluent Platform 5.3] or higher
* Get the new link:https://docs.confluent.io/current/cli/installing.html[Confluent CLI] (v0.103.0 or above)


