{
 "title": "Consumers",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "client_id", "query": "label_values(client_id)" },
   { "name": "env", "label": "env", "query": "label_values(env)" }
  ]
 },
 "panels": [
  {
   "title": "Average lag per client and partition",
   "type": "graph",
   "description": "The average lag in terms of number of records for any partition.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg{job=\"consumer\"}",
     "legendFormat": "{{instance}}-{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Avg fetch size",
   "type": "graph",
   "description": "The average number of bytes fetched per request\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{job=\"consumer\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch request latency",
   "type": "graph",
   "description": "The average time taken for a fetch request.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "graph",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_fetch_total{job=\"consumer\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "graph",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_failed_authentication_rate{job=\"consumer\",env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Average and max fetch throttle time",
   "type": "graph",
   "description": "The average and thee max throttle times in ms",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{job=\"consumer\"}",
     "legendFormat": "{{client_id}} - {{instance}}-avg"
    },
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_max{job=\"consumer\"}",
     "legendFormat": "{{client_id}} - {{instance}}-max"
    }
   ]
  },
  {
   "title": "Record lead",
   "type": "graph",
   "description": "Lag between the earliest offset in partition and the consumer offset\n",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lead{job=\"consumer\", env=\"$env\",client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}}-{{instance}}-{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes consumed rate",
     "type": "graph",
     "description": "The average number of bytes consumed per second\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{job=\"consumer\", topic=\"\", client_id=~\"$client_id\", env=\"$env\"}[$__rate_interval])",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Rate of records consumed",
     "type": "graph",
     "description": "The average number of records consumed per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{job=\"consumer\", topic=\"\", client_id=\"$client_id\", env=\"$env\"}[$__rate_interval])",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Bytes consumed rate per topic",
     "type": "graph",
     "description": "The average number of bytes consumed per topic per second.\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{job=\"consumer\", topic!=\"\", client_id=\"$client_id\", env=\"$env\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Rate of records consumed per topic",
     "type": "graph",
     "description": "The average number of records consumed per second per topic.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (topic, instance) (rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{job=\"consumer\", topic!=\"\", client_id=\"$client_id\", env=\"$env\"}[$__rate_interval]))",
       "legendFormat": "{{instance}}-{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"consumer\",env=\"$env\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"consumer\",env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"producer\",env=\"$env\"}[$__rate_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current connection count",
     "type": "graph",
     "description": "Number of simultaneous connections\n",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_count",
       "legendFormat": "{{client_id}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Node reponse rate",
     "type": "graph",
     "description": "response rate per node\n",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_response_rate{job=\"consumer\"}"
      }
     ]
    }
   ]
  }
 ]
}