{
 "title": "ksqldb Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,env)"
   },
   {
    "name": "clusterid",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,ksql_cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(ksql_ksql_engine_query_stats_liveness_indicator,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Newly Created Queries",
   "type": "singlestat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_created_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Persisted Queries",
   "type": "singlestat",
   "description": "Num of persisted queries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_persistent_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Running Queries",
   "type": "singlestat",
   "description": "Num of created queries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_running_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "singlestat",
   "description": "Num of active queries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_num_active_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Rebalancing Queries",
   "type": "singlestat",
   "description": "Num of rebalancing queries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_rebalancing_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries in Error State",
   "type": "singlestat",
   "description": "Number of error query",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(ksql_ksql_engine_query_stats_error_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cluster liveness",
   "type": "graph",
   "description": "Cluster liveness",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_liveness_indicator{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle Queries",
   "type": "singlestat",
   "description": "Num of idle queries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_num_idle_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Currently Shutting Down Queries",
   "type": "singlestat",
   "description": "Num of running queries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_pending_shutdown_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Stopped Queries",
   "type": "singlestat",
   "description": "Num of not running queries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ksql_ksql_engine_query_stats_not_running_queries{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Message produced/sec",
   "type": "graph",
   "description": "Message produced/sec",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_produced_per_sec{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Message consumed/sec",
   "type": "graph",
   "description": "Message consumed/sec",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ksql_ksql_engine_query_stats_messages_consumed_per_sec{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Hosting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"}[5m])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"ksqldb\", env=\"$env\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Queries Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Queries Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ksql_ksql_metrics_ksql_queries_query_status{job=\"ksqldb\", env=\"$env\", ksql_cluster=\"$clusterid\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Poll Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    },
    {}
   ]
  },
  {
   "title": "Poll Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Process Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Process Latency (Max + Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_process_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "Commit Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Commit Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_avg"
    }
   ]
  },
  {
   "title": "Punctuate Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}_max"
    }
   ]
  },
  {
   "title": "StateStore Metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true
  },
  {
   "title": "Put Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Put if absent max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_fetch_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_fetch_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Fetch max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_put_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Delete max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 98 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_delete_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_rate{job=\"ksqldb\", env=\"$env\", thread_id=~\".+$clusterid.+\", instance=~\"$instance\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore average latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "Restore max latency",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 109 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_streams_stream_state_metrics_restore_latency_max{thread_id=~\".+$clusterid.+\"}",
     "legendFormat": "{{thread_id}}"
    }
   ]
  }
 ]
}