DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS (id INTEGER PRIMARY KEY, firstName VARCHAR(255), lastName VARCHAR(255), email VARCHAR(255), address VARCHAR(255));
COPY CUSTOMERS FROM '/tmp/table.customers' DELIMITER '|';
