apiVersion: v1
kind: Secret
metadata:
  name: kafka-client.properties
type: Opaque
stringData:
  kafka-client.properties: |-
    bootstrap.servers=kafka:9071
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="test" password="test123";
    sasl.mechanism=PLAIN
    security.protocol=SASL_PLAINTEXT

