confluentPlatformImage: &cpImage
  image: 
    tag: 5.3.1.0
 
global:
  initContainer:
    <<: *cpImage
  provider:
    registry:
      fqdn: docker.io 
    name: gcp 
    storage:
      provisioner: kubernetes.io/gce-pd 
      reclaimPolicy: Delete 
      parameters:
        type: pd-ssd 
    sasl:
      plain:
        username=test
        password=test123

manager:
  name: manager

operator:
  name: operator
  image:
    tag: 0.176.1

zookeeper:
  <<: *cpImage
  resources:
    cpu: 200m
    memory: 512Mi
  
kafka:
  <<: *cpImage
  resources:
    cpu: 200m
    memory: 1Gi
  loadBalancer:
    enabled: false
  tls:
    enabled: false
  metricReporter:
    enabled: true
  configOverrides:
    server:
    - "auto.create.topics.enabled=true"

schemaregistry:
  <<: *cpImage
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071 

connect:
  image:
    repository: cnfldemos/cp-server-connect-operator-with-datagen 
    tag: 5.3.0.0_0.1.3
  tls:
    enabled: false
  loadBalancer:
    enabled: false
  dependencies:
    kafka:
      brokerCount: 1
      bootstrapEndpoint: kafka:9071
    schemaregistry:
      enabled: true 
      url: http://schemaregistry:8081 

controlcenter:
  <<: *cpImage
  dependencies:
    c3KafkaCluster:
      zookeeper:
        endpoint: zookeeper:2181
      bootstrapEndpoint: kafka:9071
      brokerCount: 1
    connectCluster:
      enabled: true
      url: http://connectors:8083
    schemaRegistry:
      enabled: true
      url: http://schemaregistry:8081 

