apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "replicator.name" . }}
  namespace: operator
  labels:
{{ include "replicator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "replicator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "replicator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: {{ include "replicator.name" . }}-config
        configMap:
          name: {{ include "replicator.name" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["replicator"]
          args: [ "--consumer.config", "/etc/replicator-configs/consumer.properties", "--producer.config", "/etc/replicator-configs/producer.properties", "--replication.config", "/etc/replicator-configs/replication.properties", "--cluster.id", "replicator" ]
          env:
          - name: CONNECT_REPLICATION_FACTOR
            value: "3"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ include "replicator.name" . }}-config
              mountPath: /etc/replicator-configs
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
