apiVersion: v1
kind: Secret
metadata:
  name: destination-cluster-client.properties
type: Opaque
stringData:
  destination-cluster-client.properties: |-
    ssl.endpoint.identification.algorithm=https
    sasl.mechanism=PLAIN
    request.timeout.ms=20000
    bootstrap.servers={{.Values.destinationCluster.bootstrapEndpoint}}
    retry.backoff.ms=500
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{.Values.destinationCluster.username}}" password="{{.Values.destinationCluster.password}}";
    security.protocol=SASL_SSL
  destination-cluster-bootstrap: |-
    {{.Values.destinationCluster.bootstrapEndpoint}}

