replicator:
  replicas: 1 # Not suitable for production use
  tls:
    enabled: false
  loadBalancer:
    enabled: false
  dependencies:
    kafka:
      brokerCount: 1
      bootstrapEndpoint: 
    schemaregistry:
      enabled: true 
      url: http://schemaregistry:8081 


