= Pre-requisites for KSQL Workshop
Robin Moffatt <robin@confluent.io>
v1.00, September 4, 2018

[NOTE]
====
Successfully tested on: 

[options="header"]
|=================================================================================
|Host OS|Docker|Docker Compose
|Mac 10.13.6|18.06.0-ce, build 0ffa825|1.22.0, build f46880f
|Fedora 28|18.06.1-ce, build e68fc7a|1.22.0, build f46880fe
|Ubuntu 18.04| 18.06.1-ce, build e68fc7a|1.22.0, build f46880fe

====

IMPORTANT: NOT VALIDATED ON DOCKER ON WINDOWS. 

* Docker
* Docker Compose
* 8GB+ RAM
* Clone github repository
* Pull required docker images

IMPORTANT: *THIS MUST BE DONE _BEFORE_ THE WORKSHOP - The docker images are large and will take time to download. Please don't wait until the workshop as the wi-fi will not cope!*



1. Install https://docs.docker.com/compose/install/[Docker Compose] on your system. There are Mac, Windows, and Linux options available at the link.

0. Mac/Windows only:
+
In Docker’s advanced settings, increase the memory dedicated to Docker to at least 8GB.

1. Confirm that Docker has at least 8GB of memory available to it: 
+
[source,bash]
----
docker system info | grep Memory 
----
+
Should return a value greater than 8GB - if not, the Kafka stack will probably not work. 

1. Clone the workshop repo to your local machine:
+
[source,bash]
----
git clone https://github.com/confluentinc/examples.git
----

0. Did you check that Docker has at least 8GB of memory available?
** You really do need to do this

3. Pull all required docker images—this will take a while!
+
[source,bash]
----
docker pull confluentinc/cp-zookeeper:5.1.0
docker pull confluentinc/cp-enterprise-kafka:5.1.0
docker pull confluentinc/cp-schema-registry:5.1.0
docker pull confluentinc/cp-kafka-connect:5.1.0
docker pull confluentinc/cp-ksql-server:5.1.0
docker pull confluentinc/ksql-examples:5.1.0
docker pull confluentinc/cp-kafkacat
docker pull confluentinc/cp-ksql-cli:5.1.0
docker pull debezium/connect:0.8
docker pull debezium/example-mysql:0.8
docker pull docker.elastic.co/elasticsearch/elasticsearch:6.3.0
docker pull docker.elastic.co/kibana/kibana:6.3.0
----

3. You may find it useful to have `jq` installed
+
* Mac: `brew install jq`
* RHEL-based: `sudo yum install -y jq`
* Debian-based: `sudo apt install -y jq`
* Windows: `¯\_(ツ)_/¯` -> send me a PR for these instructions on how to do it :)

4. Linux only:
+ 
If you want to use the Elasticsearch part of the workshop then make sure the virtual memory mmap count limit is set appropriately. 
+
[source,bash]
----
sudo sysctl -w vm.max_map_count=262144
----
+
See the https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html[Elasticsearch docs] for more info. 
